{'name': 'Supplier Supply Location',
 'summary': '',
 'version': '10.0.0.0.0',
 'author': "Mick, Truney Inc.",
 'category': 'Purchase Management',
 'license': 'AGPL-3',
 'depends': ['sale_stock',
             'purchase',
             ],
 'data': ['views/product_supplierinfo.xml'],
 'auto_install': False,
 'installable': True,
 }